name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate API Key
        run: |
          if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "❌ ANTHROPIC_API_KEY secret is not configured"
            exit 1
          fi
          echo "✅ ANTHROPIC_API_KEY secret is configured"

      - name: Run Claude Code
        id: claude
        continue-on-error: true
        uses: anthropics/claude-code-action@v0.0.32
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Handle Claude Failure
        if: steps.claude.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const errorComment = `## ❌ Claude Code Action Failed

            The Claude code action encountered an error during execution.

            ### 🔍 Possible Issues
            - **API Key**: ANTHROPIC_API_KEY may be invalid or expired
            - **Rate Limits**: API rate limits may have been exceeded
            - **Service Issues**: Anthropic API may be experiencing issues
            - **Action Version**: v0.0.32 may have compatibility issues

            ### 🛠️ Troubleshooting Steps
            1. **Check API Key**: Verify ANTHROPIC_API_KEY secret is valid
            2. **Check Service Status**: Visit [Anthropic Status](https://status.anthropic.com/)
            3. **Try Again**: Wait a few minutes and try again
            4. **Manual Review**: Request manual code review if issues persist

            ### 📊 Technical Details
            - **Action Version**: v0.0.32
            - **Trigger**: @claude mention
            - **Timestamp**: ${new Date().toISOString()}
            - **Workflow Run**: [View Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            *Claude Code Action Error Handler*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: errorComment
            });
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Optional: Allow Claude to run specific commands
          # allowed_tools: "Bash(npm install),Bash(npm run build),Bash(npm run test:*),Bash(npm run lint:*)"
          
          # Optional: Add custom instructions for Claude to customize its behavior for your project
          # custom_instructions: |
          #   Follow our coding standards
          #   Ensure all new code has tests
          #   Use TypeScript for new files
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

