name: "Claude AI Approval Gate"

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to evaluate'
        required: true
        type: string

# Simplified concurrency management
concurrency:
  group: claude-approval-pr-${{ github.event.pull_request.number || github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  # Enhanced debugging from main branch - helps troubleshoot conditional logic issues
  debug-conditional-logic:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Debug Conditional Logic Evaluation
        run: |
          echo "🔍 CONDITIONAL LOGIC DEBUG - Claude Approval Gate Workflow"
          echo "=================================================="
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo ""

          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "📝 ISSUE COMMENT EVENT DETAILS:"
            echo "  Comment ID: ${{ github.event.comment.id }}"
            echo "  Comment User: ${{ github.event.comment.user.login }}"
            echo "  Comment User Type: ${{ github.event.comment.user.type }}"
            echo "  Comment Created: ${{ github.event.comment.created_at }}"
            echo "  Issue/PR Number: ${{ github.event.issue.number }}"
            echo "  Is Pull Request: ${{ !!github.event.issue.pull_request }}"
            echo ""

            echo "🔍 CONDITIONAL CHECKS:"
            echo "  Contains 'FINAL VERDICT': ${{ contains(github.event.comment.body, 'FINAL VERDICT') }}"
            echo "  Contains 'Claude AI PR Review Complete': ${{ contains(github.event.comment.body, 'Claude AI PR Review Complete') }}"
            echo ""

            echo "📄 COMMENT BODY PREVIEW (first 300 chars):"
            echo "${{ github.event.comment.body }}" | head -c 300
            echo ""
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "🔧 WORKFLOW DISPATCH EVENT:"
            echo "  Manual trigger detected"
            echo "  PR Number: ${{ github.event.inputs.pr_number }}"
          fi

          echo "=================================================="

  claude-approval:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Enhanced conditional logic with improved bot detection from main branch
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, 'FINAL VERDICT') &&
       contains(github.event.comment.body, 'Claude AI PR Review Complete') &&
       (github.event.comment.user.login == 'blazecommerce-automation-bot[bot]' ||
        contains(github.event.comment.user.login, 'blazecommerce-automation-bot') ||
        (github.event.comment.user.type == 'Bot' && contains(github.event.comment.user.login, 'blazecommerce'))))
    
    permissions:
      contents: read
      pull-requests: write
      actions: read
    
    steps:
      - name: Generate GitHub App Token
        id: app_token
        if: env.BC_GITHUB_APP_ID != '' && env.BC_GITHUB_APP_PRIVATE_KEY != ''
        env:
          BC_GITHUB_APP_ID: ${{ secrets.BC_GITHUB_APP_ID }}
          BC_GITHUB_APP_PRIVATE_KEY: ${{ secrets.BC_GITHUB_APP_PRIVATE_KEY }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BC_GITHUB_APP_ID }}
          private-key: ${{ secrets.BC_GITHUB_APP_PRIVATE_KEY }}

      - name: Determine PR number
        id: pr-info
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            PR_NUMBER="${{ github.event.inputs.pr_number }}"
          else
            PR_NUMBER="${{ github.event.issue.number }}"
          fi
          
          echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "🔍 Processing PR #$PR_NUMBER"

      - name: Get PR information
        id: pr-details
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr-number }}
        with:
          github-token: ${{ steps.app_token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER);

            try {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });
              
              console.log(`PR #${prNumber}: ${pr.title}`);
              console.log(`State: ${pr.state}`);
              console.log(`Head SHA: ${pr.head.sha}`);
              
              core.setOutput('pr-state', pr.state);
              core.setOutput('head-sha', pr.head.sha);
              core.setOutput('pr-title', pr.title);
              
              return pr;
            } catch (error) {
              console.error(`Error getting PR #${prNumber}:`, error);
              core.setFailed(`Failed to get PR information: ${error.message}`);
            }

      - name: Check Claude review verdict
        id: claude-verdict
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr-number }}
          HEAD_SHA: ${{ steps.pr-details.outputs.head-sha }}
        with:
          github-token: ${{ steps.app_token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER);
            const headSha = process.env.HEAD_SHA;

            // Get the comment that triggered this workflow
            let claudeComment;
            if (context.eventName === 'issue_comment') {
              claudeComment = context.payload.comment;
            } else {
              // For workflow_dispatch, get the latest Claude comment
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber
              });
              
              claudeComment = comments
                .filter(comment => 
                  comment.body.includes('FINAL VERDICT') && 
                  comment.body.includes('Claude AI PR Review Complete')
                )
                .pop(); // Get the latest one
            }
            
            if (!claudeComment) {
              console.log('❌ No Claude review comment found');
              core.setOutput('approved', 'false');
              core.setOutput('verdict', 'no-review');
              return;
            }
            
            console.log(`📝 Claude comment: ${claudeComment.body.substring(0, 200)}...`);
            
            // Simple approval logic based on comment content
            const isApproved = claudeComment.body.includes('✅ APPROVED') || 
                              claudeComment.body.includes('APPROVED FOR MERGE');
            
            console.log(`🤖 Claude verdict: ${isApproved ? 'APPROVED' : 'NOT APPROVED'}`);
            
            core.setOutput('approved', isApproved.toString());
            core.setOutput('verdict', isApproved ? 'approved' : 'rejected');
            core.setOutput('comment-id', claudeComment.id);

      - name: Auto-approve PR if Claude approved
        if: steps.claude-verdict.outputs.approved == 'true' && steps.pr-details.outputs.pr-state == 'open'
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr-number }}
        with:
          github-token: ${{ steps.app_token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER);

            try {
              // Create approval review
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                event: 'APPROVE',
                body: '✅ Auto-approved based on Claude AI review'
              });
              
              console.log(`✅ PR #${prNumber} auto-approved`);
              
              // Add approval label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['claude-approved']
              });
              
            } catch (error) {
              console.error('Error auto-approving PR:', error);
              core.setFailed(`Failed to auto-approve PR: ${error.message}`);
            }

      - name: Add rejection label if not approved
        if: steps.claude-verdict.outputs.approved == 'false' && steps.pr-details.outputs.pr-state == 'open'
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr-number }}
        with:
          github-token: ${{ steps.app_token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER);

            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['claude-review-needed']
              });
              
              console.log(`⚠️  PR #${prNumber} marked as needing review`);
              
            } catch (error) {
              console.error('Error adding label:', error);
            }

  summary:
    needs: claude-approval
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Approval Summary
        run: |
          echo "🏁 Claude Approval Summary"
          echo "========================="
          echo "Job Result: ${{ needs.claude-approval.result }}"
          
          if [ "${{ needs.claude-approval.result }}" = "success" ]; then
            echo "✅ Claude approval gate completed successfully"
          else
            echo "❌ Claude approval gate failed or was skipped"
          fi
