name: "DEBUG: PR Trigger Test"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  debug-trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    permissions:
      contents: read
      pull-requests: read
    
    steps:
      - name: Debug PR Trigger
        run: |
          echo "🔍 DEBUG: PR Trigger Test Workflow Executed!"
          echo "=========================================="
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR State: ${{ github.event.pull_request.state }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Timestamp: $(date -u)"
          echo "=========================================="
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "✅ pull_request event triggered successfully!"
          elif [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "✅ pull_request_target event triggered successfully!"
          else
            echo "❓ Unexpected event: ${{ github.event_name }}"
          fi
          
          echo "🎯 This confirms that PR events are being detected by GitHub Actions"
