name: Test Anthropic API Key
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-key:
    runs-on: ubuntu-latest
    steps:
      - name: Test Anthropic API Key
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "❌ ANTHROPIC_API_KEY secret is not set"
            exit 1
          fi
          
          echo "✅ ANTHROPIC_API_KEY secret exists"
          echo "🔍 Testing API key validity..."
          
          # Test with minimal request (costs ~$0.0001)
          response=$(curl -s -w "%{http_code}" -X POST https://api.anthropic.com/v1/messages \
            -H "Authorization: Bearer $ANTHROPIC_API_KEY" \
            -H "Content-Type: application/json" \
            -H "anthropic-version: 2023-06-01" \
            -d '{
              "model": "claude-3-haiku-20240307",
              "max_tokens": 1,
              "messages": [{"role": "user", "content": "test"}]
            }')
          
          http_code="${response: -3}"
          response_body="${response%???}"
          
          echo "HTTP Status Code: $http_code"
          
          case $http_code in
            200)
              echo "✅ API key is VALID and working"
              ;;
            401)
              echo "❌ API key is INVALID or EXPIRED"
              echo "Response: $response_body"
              exit 1
              ;;
            429)
              echo "⚠️ Rate limited - key is valid but hitting limits"
              ;;
            *)
              echo "⚠️ Unexpected response: $http_code"
              echo "Response: $response_body"
              ;;
          esac
